<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNlztfg1\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNlztfg1/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNlztfg1.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNlztfg1\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerNlztfg1\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Nlztfg1',
    'container.build_id' => 'a22eb188',
    'container.build_time' => 1539951013,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNlztfg1');
